### PR TITLE
feat: feedback + fixes

### LINKED ISSUE #213: bug: no ongoing challenge
* when no ongoing challenge, the UI doesn't show the history

### LINKED ISSUE #214: feature: better way to show claimed modal
* claimed modal: show text based on reward + stake

### PR DESCRIPTION
**Pull request by antoncoding**
1. Update claimed modal to show amounts claimed (resolves #214) (screenshot 1)
2. Fix not showing history when no ongoing challenge (resolves #213) (screenshot 2)
3. Fix negative countdown in checkin page

Screenshot 2024-09-29 at 22 15 54
Screenshot 2024-09-29 at 22 34 55

### CODE REVIEW

File: web/app/habit/checkin/components/ActivityCheckIn.tsx [hunk 1]
```diff
@@ -288,14 +288,16 @@ export default function RunCheckIn({ challenge }: { challenge: ChallengeWithChec
...
       <div className="my-4 flex w-full justify-center">
-        {/* <div className="inline-block rounded-full border-2 border-dotted border-primary bg-primary/20 px-3 py-1"> */}
-        <span className="text-sm font-semibold text-dark">
-          ⏰ Challenge {challenge.endTimestamp > now() / 1000 ? 'ends' : 'ended'} in
-        </span>
-        <span className="ml-1 text-sm font-bold text-dark">
-          {getCountdownString(challenge.endTimestamp)}
-        </span>
-        {/* </div> */}
+        {challenge.endTimestamp > now() / 1000 ? (
```
Comment (ryanycw) [inline web/app/habit/checkin/components/ActivityCheckIn.tsx:291]: Beautiful!!!

**Review by ryanycw — APPROVED** [review]
You Champ!!
